services:
  fetcharr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fetcharr
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config/config.yaml
        read_only: true
    restart: unless-stopped