# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json

blank_issues_enabled: false
contact_links:
  - name: 💬 Support via Discussions
    url: https://github.com/fetcharr/fetcharr/discussions
    about: Ask questions and discuss with other members who use Fetcharr.