# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Development and PRs

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'docs/**'
      - '.vscode/**'

  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'docs/**'
      - '.vscode/**'

jobs:
  build:
    name: Build, format and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build, format and test
        run: ./build.cmd Compile Format Test ${{ github.ref == 'refs/heads/develop' && 'BuildImage' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
