# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Development and PRs

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'
      - '.build/**'
      - 'Dockerfile'

  pull_request:
    branches:
      - '*'
    paths:
      - 'src/**'
      - '.build/**'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build:
    name: Build, format and test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, format and test
        run: ./build.cmd Compile Format Test

      - name: Push development image
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: ./build.cmd BuildImage --include-integration-tests --push-image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
