# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release and pre-release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and release
        run: ./build.cmd Release ${{ github.ref == 'refs/heads/develop' && '--pre-release' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}